language: cpp

compiler:
 - clang

env:
 - CONFIG=release QT=qt5

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake qtdeclarative5-dev qttools5-dev qttools5-dev-tools

before_script:
 - mkdir build
 - cd build
 - cmake -DUSE_QT5=$QT5 ..

script: make