######################################################################
# Automatically generated by qmake (3.0) Mon Sep 1 19:59:33 2014
######################################################################

TEMPLATE = app
TARGET = binSpector
INCLUDEPATH += . \
               view \
               view/binary \
               view/visualizer/callGraph \
               view/visualizer/controlFlowGraph \
               view/visualizer/controlAndDataFlowGraph \
               view/visualizer/memoryAllocation \
               view/mainWidget/help \
               view/mainWidget/llvm_ir \
               control/syntax/clang \
               control/codeEditor \
               control/syntax/llvm_ir

# Input
HEADERS += view/binspector.h \
           control/codeEditor/codeEditor.h \
           view/binary/basicInfo.h \
           control/syntax/clang/clangHighlighter.h \
           control/syntax/llvm_ir/llvmHighlighter.h \
           view/mainWidget/help/help.h \
           view/mainWidget/llvm_ir/llvm_ir.h \
           view/visualizer/callGraph/callGraph.h \
           view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
           view/visualizer/controlFlowGraph/controlFlowGraph.h \
           view/visualizer/memoryAllocation/memoryAllocation.h \
           view/guiFunctions.cpp
SOURCES += main.cpp \
           view/binspector.cpp \
           view/guiFunctions.cpp \
           control/codeEditor/codeEditor.cpp \
           view/binary/basicInfo.cpp \
           control/syntax/clang/clangHighlighter.cpp \
           control/syntax/llvm_ir/llvmHighlighter.cpp \
           view/mainWidget/help/help.cpp \
           view/mainWidget/llvm_ir/llvm_ir.cpp \
           view/visualizer/callGraph/callGraph.cpp \
           view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp \
           view/visualizer/controlFlowGraph/controlFlowGraph.cpp \
           view/visualizer/memoryAllocation/memoryAllocation.cpp
RESOURCES += qdarkstyle/style.qrc
QT += widgets
