#############################################################################
# Makefile for building: binSpector.app/Contents/MacOS/binSpector
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  binSpector.pro
# Template: app
# Command: /Users/michaelriedel/Qt/5.3/clang_64/bin/qmake -o Makefile binSpector.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I. -Iview -Iview/binary -Iview/visualizer/callGraph -Iview/visualizer/controlFlowGraph -Iview/visualizer/controlAndDataFlowGraph -Iview/visualizer/memoryAllocation -Iview/mainWidget/help -Iview/mainWidget/llvm_ir -Icontrol/syntax/clang -Icontrol/codeEditor -Icontrol/syntax/llvm_ir -I../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/michaelriedel/Qt/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/michaelriedel/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		view/binspector.cpp \
		control/codeEditor/codeEditor.cpp \
		view/binary/basicInfo.cpp \
		control/syntax/clang/clangHighlighter.cpp \
		control/syntax/llvm_ir/llvmHighlighter.cpp \
		view/mainWidget/help/help.cpp \
		view/mainWidget/llvm_ir/llvm_ir.cpp \
		view/visualizer/callGraph/callGraph.cpp \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp \
		view/visualizer/controlFlowGraph/controlFlowGraph.cpp \
		view/visualizer/memoryAllocation/memoryAllocation.cpp qrc_style.cpp \
		moc_binspector.cpp \
		moc_codeEditor.cpp \
		moc_basicInfo.cpp \
		moc_clangHighlighter.cpp \
		moc_llvmHighlighter.cpp \
		moc_help.cpp \
		moc_llvm_ir.cpp \
		moc_callGraph.cpp \
		moc_controlAndDataFlowGraph.cpp \
		moc_controlFlowGraph.cpp \
		moc_memoryAllocation.cpp
OBJECTS       = main.o \
		binspector.o \
		codeEditor.o \
		basicInfo.o \
		clangHighlighter.o \
		llvmHighlighter.o \
		help.o \
		llvm_ir.o \
		callGraph.o \
		controlAndDataFlowGraph.o \
		controlFlowGraph.o \
		memoryAllocation.o \
		qrc_style.o \
		moc_binspector.o \
		moc_codeEditor.o \
		moc_basicInfo.o \
		moc_clangHighlighter.o \
		moc_llvmHighlighter.o \
		moc_help.o \
		moc_llvm_ir.o \
		moc_callGraph.o \
		moc_controlAndDataFlowGraph.o \
		moc_controlFlowGraph.o \
		moc_memoryAllocation.o
DIST          = ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		binSpector.pro main.cpp \
		view/binspector.cpp \
		control/codeEditor/codeEditor.cpp \
		view/binary/basicInfo.cpp \
		control/syntax/clang/clangHighlighter.cpp \
		control/syntax/llvm_ir/llvmHighlighter.cpp \
		view/mainWidget/help/help.cpp \
		view/mainWidget/llvm_ir/llvm_ir.cpp \
		view/visualizer/callGraph/callGraph.cpp \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp \
		view/visualizer/controlFlowGraph/controlFlowGraph.cpp \
		view/visualizer/memoryAllocation/memoryAllocation.cpp
QMAKE_TARGET  = binSpector
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = binSpector.app/Contents/MacOS/binSpector

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile binSpector.app/Contents/PkgInfo binSpector.app/Contents/Resources/empty.lproj binSpector.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d binSpector.app/Contents/MacOS/ || mkdir -p binSpector.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: binSpector.pro ../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		binSpector.pro \
		qdarkstyle/style.qrc \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile binSpector.pro
../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
binSpector.pro:
qdarkstyle/style.qrc:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile binSpector.pro

qmake_all: FORCE

binSpector.app/Contents/PkgInfo: 
	@test -d binSpector.app/Contents || mkdir -p binSpector.app/Contents
	@$(DEL_FILE) binSpector.app/Contents/PkgInfo
	@echo "APPL????" >binSpector.app/Contents/PkgInfo
binSpector.app/Contents/Resources/empty.lproj: 
	@test -d binSpector.app/Contents/Resources || mkdir -p binSpector.app/Contents/Resources
	@touch binSpector.app/Contents/Resources/empty.lproj
	
binSpector.app/Contents/Info.plist: 
	@test -d binSpector.app/Contents || mkdir -p binSpector.app/Contents
	@$(DEL_FILE) binSpector.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.binSpector,g" -e "s,@EXECUTABLE@,binSpector,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >binSpector.app/Contents/Info.plist
dist: 
	@test -d .tmp/binSpector1.0.0 || mkdir -p .tmp/binSpector1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/binSpector1.0.0/ && $(COPY_FILE) --parents qdarkstyle/style.qrc .tmp/binSpector1.0.0/ && $(COPY_FILE) --parents view/binspector.h control/codeEditor/codeEditor.h view/binary/basicInfo.h control/syntax/clang/clangHighlighter.h control/syntax/llvm_ir/llvmHighlighter.h view/mainWidget/help/help.h view/mainWidget/llvm_ir/llvm_ir.h view/visualizer/callGraph/callGraph.h view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h view/visualizer/controlFlowGraph/controlFlowGraph.h view/visualizer/memoryAllocation/memoryAllocation.h view/guiFunctions.cpp .tmp/binSpector1.0.0/ && $(COPY_FILE) --parents main.cpp view/binspector.cpp control/codeEditor/codeEditor.cpp view/binary/basicInfo.cpp control/syntax/clang/clangHighlighter.cpp control/syntax/llvm_ir/llvmHighlighter.cpp view/mainWidget/help/help.cpp view/mainWidget/llvm_ir/llvm_ir.cpp view/visualizer/callGraph/callGraph.cpp view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp view/visualizer/controlFlowGraph/controlFlowGraph.cpp view/visualizer/memoryAllocation/memoryAllocation.cpp .tmp/binSpector1.0.0/ && (cd `dirname .tmp/binSpector1.0.0` && $(TAR) binSpector1.0.0.tar binSpector1.0.0 && $(COMPRESS) binSpector1.0.0.tar) && $(MOVE) `dirname .tmp/binSpector1.0.0`/binSpector1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/binSpector1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r binSpector.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_style.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp
qrc_style.cpp: qdarkstyle/style.qrc \
		qdarkstyle/rc/Vsepartoolbar.png \
		qdarkstyle/rc/up_arrow_disabled.png \
		qdarkstyle/rc/close.png \
		qdarkstyle/rc/down_arrow.png \
		qdarkstyle/rc/transparent.png \
		qdarkstyle/rc/branch_closed-on.png \
		qdarkstyle/rc/Hsepartoolbar.png \
		qdarkstyle/rc/branch_open-on.png \
		qdarkstyle/rc/right_arrow_disabled.png \
		qdarkstyle/rc/undock.png \
		qdarkstyle/rc/Hmovetoolbar.png \
		qdarkstyle/rc/up_arrow.png \
		qdarkstyle/rc/branch_open.png \
		qdarkstyle/rc/left_arrow_disabled.png \
		qdarkstyle/rc/stylesheet-vline.png \
		qdarkstyle/rc/branch_closed.png \
		qdarkstyle/rc/left_arrow.png \
		qdarkstyle/rc/right_arrow.png \
		qdarkstyle/rc/checkbox.png \
		qdarkstyle/rc/stylesheet-branch-end.png \
		qdarkstyle/rc/stylesheet-branch-more.png \
		qdarkstyle/rc/Vmovetoolbar.png \
		qdarkstyle/rc/down_arrow_disabled.png \
		qdarkstyle/rc/sizegrip.png \
		qdarkstyle/style.qss
	/Users/michaelriedel/Qt/5.3/clang_64/bin/rcc -name style qdarkstyle/style.qrc -o qrc_style.cpp

compiler_moc_header_make_all: moc_binspector.cpp moc_codeEditor.cpp moc_basicInfo.cpp moc_clangHighlighter.cpp moc_llvmHighlighter.cpp moc_help.cpp moc_llvm_ir.cpp moc_callGraph.cpp moc_controlAndDataFlowGraph.cpp moc_controlFlowGraph.cpp moc_memoryAllocation.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_binspector.cpp moc_codeEditor.cpp moc_basicInfo.cpp moc_clangHighlighter.cpp moc_llvmHighlighter.cpp moc_help.cpp moc_llvm_ir.cpp moc_callGraph.cpp moc_controlAndDataFlowGraph.cpp moc_controlFlowGraph.cpp moc_memoryAllocation.cpp
moc_binspector.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/memoryAllocation/memoryAllocation.h \
		view/binspector.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/binspector.h -o moc_binspector.cpp

moc_codeEditor.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		control/codeEditor/codeEditor.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib control/codeEditor/codeEditor.h -o moc_codeEditor.cpp

moc_basicInfo.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/binary/basicInfo.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/binary/basicInfo.h -o moc_basicInfo.cpp

moc_clangHighlighter.cpp: ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		control/syntax/clang/clangHighlighter.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib control/syntax/clang/clangHighlighter.h -o moc_clangHighlighter.cpp

moc_llvmHighlighter.cpp: ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		control/syntax/llvm_ir/llvmHighlighter.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib control/syntax/llvm_ir/llvmHighlighter.h -o moc_llvmHighlighter.cpp

moc_help.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		view/mainWidget/help/help.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/mainWidget/help/help.h -o moc_help.cpp

moc_llvm_ir.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		view/mainWidget/llvm_ir/llvm_ir.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/mainWidget/llvm_ir/llvm_ir.h -o moc_llvm_ir.cpp

moc_callGraph.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/visualizer/callGraph/callGraph.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/visualizer/callGraph/callGraph.h -o moc_callGraph.cpp

moc_controlAndDataFlowGraph.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h -o moc_controlAndDataFlowGraph.cpp

moc_controlFlowGraph.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/visualizer/controlFlowGraph/controlFlowGraph.h -o moc_controlFlowGraph.cpp

moc_memoryAllocation.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/visualizer/memoryAllocation/memoryAllocation.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector -I/Users/michaelriedel/Developer/binSpector/view -I/Users/michaelriedel/Developer/binSpector/view/binary -I/Users/michaelriedel/Developer/binSpector/view/visualizer/callGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/controlAndDataFlowGraph -I/Users/michaelriedel/Developer/binSpector/view/visualizer/memoryAllocation -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/help -I/Users/michaelriedel/Developer/binSpector/view/mainWidget/llvm_ir -I/Users/michaelriedel/Developer/binSpector/control/syntax/clang -I/Users/michaelriedel/Developer/binSpector/control/codeEditor -I/Users/michaelriedel/Developer/binSpector/control/syntax/llvm_ir -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/visualizer/memoryAllocation/memoryAllocation.h -o moc_memoryAllocation.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/memoryAllocation/memoryAllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

binspector.o: view/binspector.cpp view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/memoryAllocation/memoryAllocation.h \
		view/mainWidget/help/help.h \
		view/mainWidget/llvm_ir/llvm_ir.h \
		control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		view/guiFunctions.cpp \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QFontMetrics \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o binspector.o view/binspector.cpp

codeEditor.o: control/codeEditor/codeEditor.cpp ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QTextBlock \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		control/codeEditor/codeEditor.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeEditor.o control/codeEditor/codeEditor.cpp

basicInfo.o: view/binary/basicInfo.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/guiFunctions.cpp \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QFontMetrics \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basicInfo.o view/binary/basicInfo.cpp

clangHighlighter.o: control/syntax/clang/clangHighlighter.cpp control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clangHighlighter.o control/syntax/clang/clangHighlighter.cpp

llvmHighlighter.o: control/syntax/llvm_ir/llvmHighlighter.cpp control/syntax/llvm_ir/llvmHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o llvmHighlighter.o control/syntax/llvm_ir/llvmHighlighter.cpp

help.o: view/mainWidget/help/help.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		view/mainWidget/help/help.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o view/mainWidget/help/help.cpp

llvm_ir.o: view/mainWidget/llvm_ir/llvm_ir.cpp ../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		view/mainWidget/llvm_ir/llvm_ir.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		control/syntax/clang/clangHighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QSyntaxHighlighter \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		control/syntax/llvm_ir/llvmHighlighter.h \
		control/codeEditor/codeEditor.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o llvm_ir.o view/mainWidget/llvm_ir/llvm_ir.cpp

callGraph.o: view/visualizer/callGraph/callGraph.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStylePainter \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStyleOption \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		view/visualizer/callGraph/callGraph.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/memoryAllocation/memoryAllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o callGraph.o view/visualizer/callGraph/callGraph.cpp

controlAndDataFlowGraph.o: view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStylePainter \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStyleOption \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/memoryAllocation/memoryAllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlAndDataFlowGraph.o view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.cpp

controlFlowGraph.o: view/visualizer/controlFlowGraph/controlFlowGraph.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStylePainter \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStyleOption \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		view/visualizer/memoryAllocation/memoryAllocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlFlowGraph.o view/visualizer/controlFlowGraph/controlFlowGraph.cpp

memoryAllocation.o: view/visualizer/memoryAllocation/memoryAllocation.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStylePainter \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStyleOption \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		view/visualizer/memoryAllocation/memoryAllocation.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view/binspector.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/binary/basicInfo.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		view/visualizer/callGraph/callGraph.h \
		view/visualizer/controlFlowGraph/controlFlowGraph.h \
		view/visualizer/controlAndDataFlowGraph/controlAndDataFlowGraph.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memoryAllocation.o view/visualizer/memoryAllocation/memoryAllocation.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

moc_binspector.o: moc_binspector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_binspector.o moc_binspector.cpp

moc_codeEditor.o: moc_codeEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeEditor.o moc_codeEditor.cpp

moc_basicInfo.o: moc_basicInfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basicInfo.o moc_basicInfo.cpp

moc_clangHighlighter.o: moc_clangHighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clangHighlighter.o moc_clangHighlighter.cpp

moc_llvmHighlighter.o: moc_llvmHighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_llvmHighlighter.o moc_llvmHighlighter.cpp

moc_help.o: moc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_help.o moc_help.cpp

moc_llvm_ir.o: moc_llvm_ir.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_llvm_ir.o moc_llvm_ir.cpp

moc_callGraph.o: moc_callGraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_callGraph.o moc_callGraph.cpp

moc_controlAndDataFlowGraph.o: moc_controlAndDataFlowGraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controlAndDataFlowGraph.o moc_controlAndDataFlowGraph.cpp

moc_controlFlowGraph.o: moc_controlFlowGraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controlFlowGraph.o moc_controlFlowGraph.cpp

moc_memoryAllocation.o: moc_memoryAllocation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_memoryAllocation.o moc_memoryAllocation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

